routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/* Route::any('{url_param}', function() {
    abort(403, '404 Error. Page not found!');
})->where('url_param', '.*'); */

Route::post('pdfreport','SaleController@pdf')->name('pdfreport'); //PDF report test

Route::get('/reset',function ()
{
	return view('auth.passwords.reset');
});
Route::get('/user/registration', 'UserController@user_register')->name('user.registration');
Route::post('/user/registration', 'UserController@user_register_store')->name('user.registration');

// Auth::routes('register');

 // Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
// Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
// Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::get('/laravel_chart', 'ChartDataController@getMonthlyPostData');

Route::group(['middleware'=>'auth'],function(){
	Route::get('/', 'HomeController@index')->name('/');
	Route::get('profile','UserController@profile')->name('profile');
	Route::post('profile.update','UserController@update_avatar')->name('profile.update');
	Route::resource('warranty_type','WarrantyTypeController');
	Route::resource('categories','CategoryController');
	
	Route::resource('branches','BranchController');
	
	Route::resource('suppliers','SupplierController');
	Route::post('supplier_beginning_balance','SupplierController@supplierBeginningBalance');
	Route::resource('sales_man','SalesManController');
	Route::get('show_invoice/{id}','SupplierController@show_invoice')->name('show_invoice');
	Route::get('monthly_status_of_supplier','SupplierController@monthlyStatusOfSupplier')->name('monthly_status_of_supplier');
	Route::resource('customer_groups','CustomerGroupController');
	Route::resource('customers','CustomerController');
	Route::get('monthly_status_of_customer','CustomerController@monthlyStatusOfCustomer')->name('monthly_status_of_customer');
	Route::post('customer_beginning_balance','CustomerController@customerBeginningBalance');
	Route::get('customer_invoice_show/{id}','CustomerController@customer_invoice_show')->name('customer_invoice_show');
	Route::resource('attribute_sets','AttributeSetController');
	Route::resource('attributes','AttributeController');
	Route::resource('vat','VatController');
	Route::resource('brand','BrandController');
	Route::resource('bundle_product','BundleProductController');
	Route::post('change_status/{id}','BundleProductController@change_status')->name('change_status');
	Route::get('getPrice/{id}','BundleProductController@get_price');
	//Route::resource('bundle_product_details','BundleProductDetailController');
	Route::resource('transactions','TransactionController');
	Route::get('transaction_status_show/{ridtype}','TransactionController@transaction_status_show')->name('transaction_status_show');
	
	Route::resource('products','ProductController');
	Route::get('barcode','ProductController@barcodeget')->name('barcode');
	Route::get('product_tracking','ProductController@productTracking')->name('product_tracking');
	Route::post('barcode','ProductController@barcodepost')->name('barcode');
	Route::resource('expire_products','ExpirableProductDetailController');
	Route::get('datatable','PurchaseController@getIndex');
	Route::get('datatabledata','PurchaseController@anyData');
	Route::get('show_invoice_details/{invoice_no}','PurchaseController@show_invoice_details')->name('show_invoice_details');
	Route::resource('purchases','PurchaseController');
	Route::get('purchase_history/{id}','BranchInventoryController@purchase_history')->name('purchase_history');
	Route::resource('trial_balance','AccountController');
	Route::get('income_report','AccountController@income_report');
	Route::resource('purchase_returns','PurchaseReturnController');
	Route::resource('journals','JournalController');
	Route::get('attributes_set_ajaxdata/{attr_set_id}','AttributeSetController@ajaxDataAttr');
	Route::get('warranty_type_data','WarrantyTypeController@warrenty_data');
	Route::resource('payment_method','PaymentMethodController');
	Route::post('add_payment_method_balance','PaymentMethodController@add_payment_method_balance');

	Route::resource('sales','SaleController');
	Route::resource('sales_return','SaleReturnController');
	Route::get('sales_report','SaleController@sales_report')->name('sales_report');
	Route::get('purchase_history_for_return','PurchaseReturnController@purchase_history_for_return');
	Route::get('sales_history_for_return','SaleReturnController@sales_history_for_return');
	Route::get('sales_details_report/{id}','SaleController@sales_details_report')->name('sales_details_report');
	Route::get('get_customer','SaleController@get_customer')->name('get_customer');
	Route::get('productSearch/{searchBy}','SaleController@productSearch')->name('productSearch');


	Route::get('add_to_cart/{productid}/{purchaseid}/{cust_group_id?}','SaleController@add_item_to_cart')->name('add_to_cart');
	Route::get('hold_customer_cart','SaleController@holdCustomerCart')->name('hold_customer_cart');
	Route::get('hold_back_customer_cart','SaleController@holdBackCustomerCart')->name('hold_back_customer_cart');
	Route::get('add_to_cart_bundle/{productid}','SaleController@add_bundle_item_to_cart')->name('add_to_cart_bundle');
	Route::get('update_cart_quentity/{rowid}/{qty}','SaleController@update_cart_quentity')->name('update_cart_quentity');
	Route::get('update_cart_discount/{coupon_no}','SaleController@update_cart_discount')->name('update_cart_discount');
	Route::get('set_customer_info/{customer_search_input}','SaleController@set_customer_info')->name('set_customer_info');
	Route::get('remove_item/{rowid}','SaleController@remove_item')->name('remove_item');
	Route::get('payment_model/{hello}','SaleController@returnCartTable')->name('payment_model');
	Route::get('view_product_details/{product_id}','SaleController@view_product_details')->name('view_product_details');
	Route::get('product_details/{product_id}','ProductController@get_product_details')->name('product_details');
	Route::get('invoice_details/{invoice}','PurchaseController@get_invoice_details')->name('invoice_details');
	Route::get('view_bundle_product_details/{product_id}','SaleController@view_bundle_product_details')->name('view_bundle_product_details');

	Route::resource('inventories','BranchInventoryController');
	Route::get('inventories_cart/{id}','BranchInventoryController@addToCart');

	Route::resource('discount_offers',"DiscountOfferController");
	Route::resource('customer_criterias',"CustomerCriteriaController");
	Route::resource('cheque_infos',"ChequeInfoController");
	Route::post('change_criteria_status/{id}','CustomerCriteriaController@criteria_status')->name('change_criteria_status');
	Route::post('change_discount_status/{id}','DiscountOfferController@discount_status')->name('change_discount_status');
	Route::get('find_purchase_id/{product_id}','DiscountOfferController@ajaxpurchaseid')->name('find_purchase_id');
	Route::get('find_product_for_discount/{product_id}/{invoice_no}','DiscountOfferController@find_product_for_discount')->name('find_product_for_discount');
	Route::post('change_user_status/{id}','HomeController@change_status')->name('change_user_status');
	Route::resource('warranty_product_detail','WarrantyProductDetailController');
	Route::get('expense_show','PrimarySettingsController@expenseShow')->name('expense_show');
	Route::get('payment_show','TransactionController@paymentShow')->name('payment_show');
	Route::get('record_expense','PrimarySettingsController@expenseCreate')->name('record_expense');
	Route::resource('primary_settings','PrimarySettingsController');
	Route::resource('invoice_setting','InvoiceSettingController');
	//Route::get('find_purchase_details/{product_purchase_id}','DiscountOfferController@ajaxpurchasedetails');
	//Route::get('sales/test/{sale}','SaleController@show')->name('sales.show');
	Route::get('/laravel_google_chart', 'HomeController@googlepiechart');
	Route::get('inventory_details/{id}','HomeController@show')->name('dashboard.branch');
});

resources/views/admin/transactions/cash_flow.blade.php
@extends('layouts.admin')

@section('content')

<div class="row">
<div class="col-md-12 d-flex align-items-stretch grid-margin">
  <div class="row flex-grow row_table_responsive">
	<div class="col-md-12">
	  <div class="card">
		<div class="card-body">
        <h2 class="text-center">Cash Flow Statement</h2>
        @if(Auth::user()->user_type=="superadmin")
        <h4 class="text-center">Showing All Branches</h4>
        @else
        <h4 class="text-center">Showing {{Auth::user()->branch->name}} Branch</h4>
        @endif
        <p class="card-description text-center">
            For the month of {{request('month')? date('F-Y', strtotime(request('month'))):date('F-Y') }}
            <form method="get" action="{{url('').'/transactions'}}">
                <div class="input-group col-md-6 float-right">
                    <label for="example-search-input2">Month :</label>
                    <input class="form-control py-2" name="month" type="month" id="example-search-input2" value="{{request('month')? date('Y-m', strtotime(request('month'))):date('Y-m') }}">
                    <span class="input-group-append">
                        <button class="btn btn-primary" type="submit">
                            <i class="mdi mdi-magnify"></i>
                        </button>
                        {{-- <a href="{{route('record_expense')}}" class="btn btn-primary">Add New</a > --}}
                    </span>
                </div>
            </form>
      <div class="table-responsive">
                    <table class="table table-bordered">
                      <thead>
                        <tr>
                          <th>Transaction ID</th>
                          <th>Date</th>
                          <th>Account Title</th>
                          <th>description</th>
                          <th>Debit</th>
                          <th>Credit</th>
                        </tr>
                      </thead>
                      <tbody>
                      <?php
            
                        $amount=0;
                        $damount=0;
                        //$tspan=2;
                        ?>
					  @forelse($cash_flows as $jr)
                        <tr>
                        
                       
                            <td>{{$jr->transaction_id}}</td>
                           <?php $time=strtotime($jr->created_at);
                            $date=date("d-M-Y",$time);?>
                            <td>{{$date}}</td>
                          
                            
                            <td>{{$jr->transaction->event_type}}</td>   
                            <td>{{$jr->description}}</td>                          
                       
                         
                          @if($jr->journal_type==0)
                          <td>{{number_format($jr->amount,2)}}</td>
                         <?php $damount=$damount+$jr->amount;?>
                          @else
                          <td></td>
                          @endif
                          @if($jr->journal_type==1)
                          <td>{{number_format($jr->amount,2)}}</td>
                          <?php $amount=$amount+$jr->amount;?>
                          @else
                          <td></td>
                          @endif
                          
                        </tr>
					@empty
						<tr>
							<td colspan="8">There is no records available</td>
						</tr>
					@endforelse
                      </tbody>
                      <tfoot>
                        <th colspan="4" class="text-right">Total Transaction :</th>
                        <th>
                            @if($damount>$amount)
                            {{number_format($damount-$amount,2)}}
                            @endif</th>
                        <th>
                                @if($amount>$damount)
                                {{number_format($amount-$damount,2)}} 
                                @endif</th>
                       
                      </tfoot>
                    </table>
                  </div>
		</div>
	  </div>
	</div>
  </div>
</div>

</div>

@endsection

resources/views/admin/transactions/payment_transaction.blade.php
@extends('layouts.admin') 
@section('content')

<div class="row">
  <div class="col-md-6 d-flex align-items-stretch grid-margin">
    <div class="row flex-grow">
      <div class="col-12">
        <div class="card">
          <div class="card-body">
          <form action="{{route('transactions.store')}}" method="post">
            @csrf
            @if(Gate::allows('isSuperadmin'))
            <div class="form-group">
                <label for="branch_id">Branch</label>
                <select required class="form-control" id="branch_id" name="branch_id">
                    <option value="">Select branch</option>
                    @forelse($branches as $bp)
                    <option value="{{$bp->id}}">{{$bp->name}}</option>
                    @empty
                    <option>{{'There is no branch'}}</option>
                    @endforelse
                </select>
            </div>
            @else
            <input type="hidden" name="branch_id" id="branch_id" value="{{ Auth::user()->branch_id }}">
            @endif

            
            
            
            <div class="form-group">
                {{-- <label for="transaction_type">Transaction Type</label> --}}
                <select required class="form-control" id="transaction_type" name="transaction_type" onchange="get_form_element()">
                 <option value="0" selected>Pay To Supplier</option>
                 <option value="1">Receive From Customer</option>
               </select>
            </div>




            <div id="payable_field" style="display:block">   
                <div class="form-group">
                    <label for="supplier_id">Supplier</label>
                    <select  class="form-control" id="supplier_id" name="supplier_id" onchange="getRelatedPartyInfo(this.value)">
                            <option value="">Select Supplier</option>
                        @forelse($suppliers as $sp)
                            <option value="{{$sp->id}}">{{$sp->supplier_name}}</option>
                        @empty
                            <option>{{'There is no supplier'}}</option>
                        @endforelse
                    </select>
                </div>
            </div>
            
            <div id="receivable_field" style="display:none">   
                <div class="form-group">
                    <label for="customer_id">Customer</label>
                    <select  class="form-control" id="customer_id" name="customer_id" onchange="getRelatedPartyInfo(this.value)">
                            <option value="">Select Customer</option>
                        @forelse($customers as $customer)
                            <option value="{{$customer->id}}">{{$customer->customer_name}}</option>
                        @empty
                            <option>{{'There is no Customer'}}</option>
                        @endforelse
                    </select>
                </div>
            </div>
            
            <div class="form-group">
                <label for="payment_method_id">Payment Method</label>
                <select required class="form-control" id="payment_method_id" name="payment_method_id"
                    onchange="addpaidvalue()">
                    <option value="">Select Payment Method</option>
                    @foreach($payment_methods as $pm)
                    {{-- gggg --}}
                    @php
                    $cashIn = 0; 
                    $cashOut = 0;
                    $payment_method =  $pm->method_type==1?10:2;
                    @endphp
                
                @foreach ($pm->journals as $js)
                    @if ($js->journal_type == 0 && $js->accounts_id == $payment_method)
                       @php
                           $cashIn = $cashIn + $js->amount;
                       @endphp
                    @endif
                @endforeach
               
                @foreach ($pm->journals as $js)
                    @if ($js->journal_type == 1 && $js->accounts_id == $payment_method)
                       @php
                           $cashOut = $cashOut + $js->amount;
                       @endphp
                    @endif
                @endforeach
               
                    {{-- hhhhh --}}
                    <option value="{{$pm->id." | ".$pm->method_type }}" @if($pm->method_type==0 && ($cashIn-$cashOut)<=0){{"disabled"}} class="text-danger disable_option" @endif>{{$pm->method_title}} &nbsp;&nbsp;&nbsp;&nbsp; balance:  {{$cashIn-$cashOut}}</option>
                    @endforeach
                </select>
            </div>
            <div class="form-group" id="payment_tk">
        
            </div>
            <div class="form-group" id="date_field">
        
            </div>
            <div class="form-group">
                <label for="discount">Discount</label>
                <input type="number" class="form-control" name="discount" id="discount">
            </div>
            <div class="form-group">
                <label for="representative">Representative 
                    {{-- <span class="text-danger">(Name of represented person)</span> --}}
                </label>
                <input type="text" class="form-control" name="representative" id="representative">
            </div>
            <div class="form-group" id="pro_details"></div> 
               
          <button type="submit" class="btn btn-success mr-2">Submit</button>
          <a href="{{route('journals.index')}}" class="btn btn-danger">Cancel</a>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
</div>


<script>

function get_form_element(){
    var ttype=document.getElementById('transaction_type').value;
    if(ttype==1){
        $('#payable_field').css('display','none');
        $('#receivable_field').css('display','block');
        $("#customer_id").select2( {
            placeholder: "Select Customer",
            allowClear: true
        } );
        $('.disable_option').each(function(){
            $(this).attr('disabled',false);
        });
    }else if(ttype==0){
        $('#customer_id').val(null);
        $('#payable_field').css('display','block');
        $('#receivable_field').css('display','none');
        $("#supplier_id").select2( {
            placeholder: "Select Supplier",
            allowClear: true
        } );
        $('.disable_option').each(function(){
            $(this).attr('disabled',true);
        });
    }
}
function getRelatedPartyInfo(id){
    var ttype=document.getElementById('transaction_type').value;
    var route = "{{url('')}}/transaction_status_show/"+id+'|'+ttype;
    var returndata="";
        $.get(route, function(data) {
            console.log(data);
            if(ttype==1){
                var url_route="{{url('')}}/customers/"+id;
                returndata="<a href='"+url_route+"' title='Click To Get Details' class='btn btn-block btn-primary'>Receivable Amount : <b> "+(data.split('|')[0]-data.split('|')[1]).toFixed(2)+"<b></a>";
                $('#pro_details').empty();
                $('#pro_details').html(returndata);
            }else if(ttype==0){
                var url_route="{{url('')}}/suppliers/"+id;
                returndata="<a href='"+url_route+"' title='Click To Get Details' class='btn btn-block btn-danger'>Payable Amount : <b> "+(data.split('|')[1]-data.split('|')[0]).toFixed(2)+"<b></a>";
                $('#pro_details').empty();
                $('#pro_details').html(returndata);

            }
        });
}

//input field for paid Amount
function addpaidvalue(){
    
    var payment_method_id = document.getElementById("payment_method_id").value;
    var customer_id = document.getElementById("customer_id").value;
    $('#payment_tk').empty(paid_amount);
    payment_method_id=payment_method_id.split(" | ");
    console.log(payment_method_id[0]);
    if(payment_method_id[0]){
        var paid_amount="<label for='paid_amount'>Amount</label>";
        paid_amount+="<input type='number' class='form-control' name='paid_amount' id='paid_amount' step='.01'>";
        if(payment_method_id[1]==1){
        paid_amount+="<label for='check_no'>Check No</label><input type='text' class='form-control' name='check_no' id='check_no' onblur='check_disposal_field()'>";
        }
        $('#payment_tk').prepend(paid_amount);
    }
 }
//extra field for cheque disposal date 
function check_disposal_field(){
    var payment_method_id = document.getElementById("payment_method_id").value;
    $('#date_field').empty(paid_amount);
    payment_method_id=payment_method_id.split(" | ");
    if(payment_method_id[1]==1){
        var paid_amount="<label for='cheque_disposal_date'>Cheque Disposal Date</label>";
        paid_amount+="<input type='date' class='form-control' name='cheque_disposal_date' id='cheque_disposal_date'>";
        $('#date_field').prepend(paid_amount);
    }
 }

</script>
@endsection
@push('js')
<script>
    $(document).ready(function() {
        $("#supplier_id").select2( {
            placeholder: "Select Supplier",
            allowClear: true
        } );
       
    });
</script>
<script type="text/javascript" src="{{asset('admin/js/select-togglebutton.js')}}"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $('#transaction_type').togglebutton();
        })
    </script>    
@endpush

resources/views/admin/transactions/transaction_report.blade.php
@extends('layouts.admin')

@section('content')

<div class="row">
    <div class="col-md-10 d-flex align-items-stretch grid-margin">
        <div class="row flex-grow">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <h2 class="text-center"> {{(isset($_GET['search_view']) && $_GET['search_view']==1)?'Receipts ':'Payments '}}Reports</h2>
                        @if(Auth::user()->user_type=="superadmin")
                        <h4 class="text-center">Showing All Branches</h4>
                        @else
                        <h4 class="text-center">Showing {{Auth::user()->branch->name}} Branch</h4>
                        @endif
                        <p class="card-description text-center">
							<form method="get" action="{{route('payment_show')}}">
								<div class="form-group">
									<select required class="form-control" id="view_type" name="search_view"  onchange="this.form.submit()">
									 <option value="0" {{isset($_GET['search_view'])?'':'selected'}}>Payments View</option>
									 <option value="1" {{(isset($_GET['search_view']) && $_GET['search_view']==1)?'selected':''}}>Receipts View</option>
								   </select>
								</div>
                                <div class="input-group col-md-6 float-right">
                                    <label for="example-search-input1">From :</label>
                                    <input class="form-control py-2" @if(isset($_GET['searchbyfrom']))
                                        value="{{$_GET['searchbyfrom']}}" @else value="{{date('Y-m-01')}}" @endif
                                        name="searchbyfrom" type="date" id="example-search-input1">
                                    <label for="example-search-input2">To :</label>
                                    <input class="form-control py-2" placeholder="To.." name="searchbyto" type="date"
                                        id="example-search-input2" @if(isset($_GET['searchbyto']))
                                        value="{{$_GET['searchbyto']}}" @else value="{{date('Y-m-t')}}" @endif>
                                    <span class="input-group-append">
                                        <button class="btn btn-primary" type="submit">
                                            <i class="mdi mdi-magnify"></i>
                                        </button>
                                    </span>

                                </div>
                            </form>
                        </p>
                        <div class="table-responsive">
                            <table class="table table-bordered" id="accordion" style="width:100%">
                                <thead>
                                    <tr>
                                        <th>Transaction No</th>
                                        <th>Date</th>
                                        <th>{{(isset($_GET['search_view'])&& $_GET['search_view']==1)?'Received':'Paid'}} Via</th>
                                        <th>Amount</th>
                                        <th>{{(isset($_GET['search_view'])&& $_GET['search_view']==1)?'Received From':'Paid To'}}</th>
                                        <th>{{(isset($_GET['search_view'])&& $_GET['search_view']==1)?'Received ':'Paid '}}By</th>
                                    </tr>
                                </thead>
                                <tbody>
                                   
                        @forelse($payments as $key=>$payments_status)
								<tr> 
								{{-- class="collapsed" data-toggle="collapse" href="#collapseOne{{$key}}" aria-expanded="true" aria-controls="collapseOne" style="cursor: pointer;" --}}
								<th><a class="btn link" target="_blank" href="{{route('transactions.show',$payments_status->id)}}"> {{$payments_status->id}}</a></th>
                            @php $time=strtotime($payments_status->created_at);
                            $date=date("d-M-Y",$time); @endphp
                                        <td>{{$date}}</td>
                                        @php
            
                                        $saleAmt=0;
                                        $expenseAmt=0;
                                        $paymentMethod='';
                                        @endphp
                                    @foreach($payments_status->journals as $jr)
                                        @if($jr->related_party_type=='supplier' && $jr->journal_type==0)
                                        @php 
                                        $expenseAmt=$expenseAmt+$jr->amount;
                                        @endphp
										@endif
										@if($jr->related_party_type=='customer' && $jr->journal_type==1)
                                        @php 
                                        $expenseAmt=$expenseAmt+$jr->amount;
                                        @endphp
                                        @endif            
                                    @endforeach
                                    <td>{{$payments_status->journals->first()->paymentmethod!=null?$payments_status->journals->first()->paymentmethod->method_title:''}}</td>
                                    <td>{{number_format($expenseAmt,2)}}</td>
                                    <td>{{isset($_GET['search_view'])?$payments_status->journals->first()->customer->customer_name:$payments_status->journals->first()->supplier->supplier_name}}</td>
                                    <td title="{{$payments_status->branch->name}}">{{$payments_status->user->name}}</td>
                        </tr>
                                    @empty
                                    <tr>
                                        <td colspan="8">There is no records available</td>
                                    </tr>
                                    @endforelse
                                </tbody>
                               
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

@endsection
@push('js')
<script type="text/javascript" src="{{asset('admin/js/select-togglebutton.js')}}"></script>

        <script type="text/javascript">
            $(document).ready(function() {
                $('#view_type').togglebutton();
            })
        </script>    
@endpush