routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/* Route::any('{url_param}', function() {
    abort(403, '404 Error. Page not found!');
})->where('url_param', '.*'); */

Route::post('pdfreport','SaleController@pdf')->name('pdfreport'); //PDF report test

Route::get('/reset',function ()
{
	return view('auth.passwords.reset');
});
Route::get('/user/registration', 'UserController@user_register')->name('user.registration');
Route::post('/user/registration', 'UserController@user_register_store')->name('user.registration');

// Auth::routes('register');

 // Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
// Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
// Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::get('/laravel_chart', 'ChartDataController@getMonthlyPostData');

Route::group(['middleware'=>'auth'],function(){
	Route::get('/', 'HomeController@index')->name('/');
	Route::get('profile','UserController@profile')->name('profile');
	Route::post('profile.update','UserController@update_avatar')->name('profile.update');
	Route::resource('warranty_type','WarrantyTypeController');
	Route::resource('categories','CategoryController');
	
	Route::resource('branches','BranchController');
	
	Route::resource('suppliers','SupplierController');
	Route::post('supplier_beginning_balance','SupplierController@supplierBeginningBalance');
	Route::resource('sales_man','SalesManController');
	Route::get('show_invoice/{id}','SupplierController@show_invoice')->name('show_invoice');
	Route::get('monthly_status_of_supplier','SupplierController@monthlyStatusOfSupplier')->name('monthly_status_of_supplier');
	Route::resource('customer_groups','CustomerGroupController');
	Route::resource('customers','CustomerController');
	Route::get('monthly_status_of_customer','CustomerController@monthlyStatusOfCustomer')->name('monthly_status_of_customer');
	Route::post('customer_beginning_balance','CustomerController@customerBeginningBalance');
	Route::get('customer_invoice_show/{id}','CustomerController@customer_invoice_show')->name('customer_invoice_show');
	Route::resource('attribute_sets','AttributeSetController');
	Route::resource('attributes','AttributeController');
	Route::resource('vat','VatController');
	Route::resource('brand','BrandController');
	Route::resource('bundle_product','BundleProductController');
	Route::post('change_status/{id}','BundleProductController@change_status')->name('change_status');
	Route::get('getPrice/{id}','BundleProductController@get_price');
	//Route::resource('bundle_product_details','BundleProductDetailController');
	Route::resource('transactions','TransactionController');
	Route::get('transaction_status_show/{ridtype}','TransactionController@transaction_status_show')->name('transaction_status_show');
	
	Route::resource('products','ProductController');
	Route::get('barcode','ProductController@barcodeget')->name('barcode');
	Route::get('product_tracking','ProductController@productTracking')->name('product_tracking');
	Route::post('barcode','ProductController@barcodepost')->name('barcode');
	Route::resource('expire_products','ExpirableProductDetailController');
	Route::get('datatable','PurchaseController@getIndex');
	Route::get('datatabledata','PurchaseController@anyData');
	Route::get('show_invoice_details/{invoice_no}','PurchaseController@show_invoice_details')->name('show_invoice_details');
	Route::resource('purchases','PurchaseController');
	Route::get('purchase_history/{id}','BranchInventoryController@purchase_history')->name('purchase_history');
	Route::resource('trial_balance','AccountController');
	Route::get('income_report','AccountController@income_report');
	Route::resource('purchase_returns','PurchaseReturnController');
	Route::resource('journals','JournalController');
	Route::get('attributes_set_ajaxdata/{attr_set_id}','AttributeSetController@ajaxDataAttr');
	Route::get('warranty_type_data','WarrantyTypeController@warrenty_data');
	Route::resource('payment_method','PaymentMethodController');
	Route::post('add_payment_method_balance','PaymentMethodController@add_payment_method_balance');

	Route::resource('sales','SaleController');
	Route::resource('sales_return','SaleReturnController');
	Route::get('sales_report','SaleController@sales_report')->name('sales_report');
	Route::get('purchase_history_for_return','PurchaseReturnController@purchase_history_for_return');
	Route::get('sales_history_for_return','SaleReturnController@sales_history_for_return');
	Route::get('sales_details_report/{id}','SaleController@sales_details_report')->name('sales_details_report');
	Route::get('get_customer','SaleController@get_customer')->name('get_customer');
	Route::get('productSearch/{searchBy}','SaleController@productSearch')->name('productSearch');


	Route::get('add_to_cart/{productid}/{purchaseid}/{cust_group_id?}','SaleController@add_item_to_cart')->name('add_to_cart');
	Route::get('hold_customer_cart','SaleController@holdCustomerCart')->name('hold_customer_cart');
	Route::get('hold_back_customer_cart','SaleController@holdBackCustomerCart')->name('hold_back_customer_cart');
	Route::get('add_to_cart_bundle/{productid}','SaleController@add_bundle_item_to_cart')->name('add_to_cart_bundle');
	Route::get('update_cart_quentity/{rowid}/{qty}','SaleController@update_cart_quentity')->name('update_cart_quentity');
	Route::get('update_cart_discount/{coupon_no}','SaleController@update_cart_discount')->name('update_cart_discount');
	Route::get('set_customer_info/{customer_search_input}','SaleController@set_customer_info')->name('set_customer_info');
	Route::get('remove_item/{rowid}','SaleController@remove_item')->name('remove_item');
	Route::get('payment_model/{hello}','SaleController@returnCartTable')->name('payment_model');
	Route::get('view_product_details/{product_id}','SaleController@view_product_details')->name('view_product_details');
	Route::get('product_details/{product_id}','ProductController@get_product_details')->name('product_details');
	Route::get('invoice_details/{invoice}','PurchaseController@get_invoice_details')->name('invoice_details');
	Route::get('view_bundle_product_details/{product_id}','SaleController@view_bundle_product_details')->name('view_bundle_product_details');

	Route::resource('inventories','BranchInventoryController');
	Route::get('inventories_cart/{id}','BranchInventoryController@addToCart');

	Route::resource('discount_offers',"DiscountOfferController");
	Route::resource('customer_criterias',"CustomerCriteriaController");
	Route::resource('cheque_infos',"ChequeInfoController");
	Route::post('change_criteria_status/{id}','CustomerCriteriaController@criteria_status')->name('change_criteria_status');
	Route::post('change_discount_status/{id}','DiscountOfferController@discount_status')->name('change_discount_status');
	Route::get('find_purchase_id/{product_id}','DiscountOfferController@ajaxpurchaseid')->name('find_purchase_id');
	Route::get('find_product_for_discount/{product_id}/{invoice_no}','DiscountOfferController@find_product_for_discount')->name('find_product_for_discount');
	Route::post('change_user_status/{id}','HomeController@change_status')->name('change_user_status');
	Route::resource('warranty_product_detail','WarrantyProductDetailController');
	Route::get('expense_show','PrimarySettingsController@expenseShow')->name('expense_show');
	Route::get('payment_show','TransactionController@paymentShow')->name('payment_show');
	Route::get('record_expense','PrimarySettingsController@expenseCreate')->name('record_expense');
	Route::resource('primary_settings','PrimarySettingsController');
	Route::resource('invoice_setting','InvoiceSettingController');
	//Route::get('find_purchase_details/{product_purchase_id}','DiscountOfferController@ajaxpurchasedetails');
	//Route::get('sales/test/{sale}','SaleController@show')->name('sales.show');
	Route::get('/laravel_google_chart', 'HomeController@googlepiechart');
	Route::get('inventory_details/{id}','HomeController@show')->name('dashboard.branch');
});

app/Discount_offer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Discount_offer extends Model
{
    public function customer_groups(){
        return $this->belongsToMany(Customer_group::class)->withTimestamps();
    } 
	
	public function customer_criterias(){
        return $this->belongsToMany(CustomerCriteria::class)->withTimestamps();
    }
	
	public function product(){
        return $this->belongsTo('App\Product','product_id');
    }
}

resources/views/admin/discount_offer/edit.blade.php
@extends('layouts.admin')
@section('content')
<div class="row">
    <div class="col-md-12 d-flex align-items-stretch grid-margin">
        <div class="row flex-grow">
            <div class="col-md-1"></div>
            <div class="col-md-10 bg-secondary">
                <div class="card bg-secondary">
                    <div class="card-body">
                        <h4 class="text-center">Discount Form</h4>
                        <form class="forms-sample" method="post" action="{{  route('discount_offers.update', $discount_offer->id)}}">
                            @csrf
                            @method('put')
                            <div class="form-group row">
                                <label for="discount_title" class="col-sm-2">Discount Title</label>
                                <div class="col-sm-10">
                                    <input type="text" value="{{ $discount_offer->discount_title }}" name="discount_title" id="discount_title" class="form-control">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="offer_from" class="col-sm-2">Offer From</label>
                                <div class="col-sm-10">
                                    <input type="date" value="{{ $discount_offer->offer_from }}" name="offer_from" id="offer_from" class="form-control">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="offer_to" class="col-sm-2">Offer To</label>
                                <div class="col-sm-10">
                                    <input type="date" value="{{ $discount_offer->offer_to }}" name="offer_to" id="offer_to" class="form-control">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">Discount Type</label>
                                <div class="col-sm-2">
                                    <div class="form-radio">
                                        <label class="form-check-label">
                                            <input type="radio" class="form-check-input" value="0" name="discount_type"
                                                id="discount_percent" {{ $discount_offer->discount_percent?'checked':'' }} onclick="changeAddon(0)">
                                            <i class="input-helper">Percent</i></label>
                                    </div>
                                </div>
                                <div class="col-sm-2">
                                    <div class="form-radio">
                                        <label class="form-check-label">
                                            <input type="radio" class="form-check-input" value="1" name="discount_type"
                                                id="discount_amount" {{ $discount_offer->discount_amount?'checked':'' }}  onclick="changeAddon(1)">
                                            <i class="input-helper">Amount</i></label>
                                    </div>
                                </div>
                                <div class="input-group col-sm-6">
                                    <input type="number" class="form-control" name="discount_rate" id="hidden_1" value="{{ $discount_offer->discount_percent?$discount_offer->discount_percent*100:$discount_offer->discount_amount }}" aria-describedby="basic-addon-percent" step=".01">
                                    <div class="input-group-append">
                                    <span class="input-group-text text-info" id="basic-addon-percent">%</span></div>
                                </div>
                            </div>
                            {{--  <div class="form-group row">
                                <label for="customer_group" class="col-sm-2">Select Customer Group</label>
                                <div class="col-sm-10">
                                    <select name="customerGroup[]" class="form-control " data-live-search="true" id="customer_group"
                                        multiple>
                                        @foreach($groups as $grp)
                                        <option value="{{ $grp->id}}">{{ $grp->customer_group_title }}</option>
                                        @endforeach
                                    </select>
                                    <p><strong class="text-danger">'Ctrl+click'</strong> for multiple select</p>                                    
                                </div>
                            </div>  --}}
                            <br>
                            {{--  
                                <div class="form-group row">
                                    <label for="customer_criteria" class="col-sm-2">Select Customer Criteria</label>
                                    <div class="col-sm-10">
                                        <select name="customerCriteria[]" class="form-control " data-live-search="true" id="customer_criteria" multiple>
                                            @foreach($criterias as $crt)
                                                @if($crt->status==1)
                                                    <option value="{{$crt->id}}">{{$crt->title}}</option>
                                                @endif
                                            @endforeach
                                        </select>
                                        <p><strong class="text-danger">'Ctrl+click'</strong> for multiple select</p>
                                    </div>
                                </div>  
                            --}}
                            <div class="row">
                                <div class="col-sm-5">
                                    <div class="form-group row">
                                            <div class="form-radio">
                                                <label class="form-check-label">
                                                    {{--onclick="hidden3()" is used for show-hide the parameterwised fields --}}
                                                    <input type="radio" class="form-check-input" value="0" name="discount_on" id="promo_code" onclick="hidden3('hidden_3','product_name','purchase_field')" {{ $discount_offer->promo_code !== null?'checked':'' }}>Promo Code <i class="input-helper"></i>
                                                </label>
                                            </div>
                                            <input type="text" style="display:{{ $discount_offer->promo_code !== null?'block':'none' }}" class="form-control" name="promo_code" id="hidden_3"   value="{{ $discount_offer->promo_code }}">
                                        </div>
                                </div>
                                <div class="col-sm-1"><label class="form-check-label">Or</label></div>
                                <div class="col-sm-6">
                                    <div class="form-group row">
                                        <div class="form-radio">
                                            <label class="form-check-label" id="discount_for_product_label">
                                                <input type="radio" class="form-check-input" value="1" name="discount_on" id="promo_code1" {{ ($discount_offer->product_id !== null && $discount_offer->purchase_id !== null)?'checked':'' }}  onclick="productname1('product_name','hidden_3','purchase_field')"/>Products Discount
                                                <i class="input-helper text-sm text-danger">
                                            </label>
                                        </div>
                                    </div>
                                    {{--productname() method used to retrive product_id when click on "choose product" field.this method is in script tag below.--}}
                                    <div class="form-control" style="display:{{ ($discount_offer->product_id !== null && $discount_offer->purchase_id !== null)?'block':'none' }}" id="product_name_div">
                                        <select class="form-control" name="product_name" id="product_name" value="" onchange="productname()">
                                            <option value="">Select Product</option>
                                            @php $pro=0; @endphp
                                                @foreach($products as $product)
                                                    @if($pro!==$product->product_id)
                                                    <option value="{{$product->product_id}}"
                                                        {{ $product->product_id==$discount_offer->product_id?'selected':''}}>{{$product->product->product_sku}}</option>
                                                    <?php $pro = $product->product_id ?>
                                                    @endif
                                                @endforeach
                                        </select>
                                    </div>
                                    <div style="display:{{ ($discount_offer->product_id !== null && $discount_offer->purchase_id !== null)?'block':'none' }}" class="form-group" id="purchase_field">
                                        <br>
                                            <label for="purchase_id">Purchase Price / Invoice No.</label>
                                            <select class="form-control" id="purchase_id" onchange="purchaseid()">
                                                <option value=''>Not Applicable</option>
                                                @forelse ($purchases as $purchase)
                                                     <option {{ $purchase->purchase->id === $discount_offer->purchase_id?'selected':''}} value="{{ $purchase->purchase->id }}"> {{ 'Inv: '.$purchase->purchase->invoice_no .' / Selling Price: '.$purchase->purchase->sell_unit_price }}</option>
                                                @empty
                                                    
                                                @endforelse
                                               
                                            </select>
                                    </div>  
                                </div>
                            </div>
                            <button type="submit" class="btn btn-success mr-2">Submit</button>
                            <a class="btn btn-danger" href="{{route('discount_offers.index')}}">Cancel</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    function productname() {
        var purchase = document.getElementById("product_name").value;

        $('#purchase_field').empty();
        if (purchase) {
            $.ajax({
                type: 'GET',
                url: "<?=url('find_purchase_id')?>"+"/"+ purchase,
                success: function (html) {
                    $('#purchase_field').prepend(html);

                }
            });
        }
    }

    function hidden3(hidden_3, product_name, purchase_field) {
        $(document).ready(function () {
            $('#hidden_3').show();
            $('#product_name').hide();
            $('#product_name_div').hide();
            $('#purchase_field').hide();
        });
    }

    function productname1(product_name, hidden_3, purchase_field) {

        $(document).ready(function () {
            $('#product_name').show();
            $('#hidden_3').hide();
            $('#purchase_field').show();
            $('#product_name_div').show();
        });

    }

</script>
@endsection

resources/views/admin/discount_offer/index.blade.php
@extends('layouts.admin') @section('content')

<div class="row">
    <div class="col-md-12 d-flex align-items-stretch grid-margin">
        <div class="row flex-grow row_table_responsive">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <h2 class="text-center">Discount Offers</h2>
                            <div class="row">
                                {{-- <div class="col-md-6"></div> --}}
                                <div class="col-md-12">
                                    <form action="{{route('discount_offers.index')}}" method="GET">
                                      <div class="input-group float-right">
                                          <input class="form-control py-2 border-primary" placeholder="Search here.." value="{{ request('search')}}" name="search" type="text" id="example-search-input" required="">
                                          <span class="input-group-append">
                                            <button class="btn btn-primary" type="submit">
                                                <i class="mdi mdi-magnify"></i>
                                            </button>
                                            <a class="btn btn-primary" title="Register New Offers" href="{{route('discount_offers.create')}}"><i class="mdi mdi-playlist-plus"></i></a>  
                                            @if (request()->query())
                                            <a class="btn btn-primary" title="Show All Offers" href="{{route('discount_offers.index')}}"><i class="mdi mdi-format-list-bulleted"></i></a> 
                                            @endif
                                          </span>
                                      </div>
                                    </form>
                                </div>
                              </div>
                          <br>
                       

                        <div class="table-responsive">
                            <table class="table table-striped table-bordered border-primary">
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Title</th>
                                        <th>Product Or Promo</th>
                                        <th>Duration</th>
                                        <th>Discount</th>
                                        <th>Status</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @forelse($discount_index as $key=>$discount)
                                    <tr>
                                        <td>{{(($discount_index->currentPage() - 1) * $discount_index->perPage() + $key+1)}}</td>
                                        <td>{{$discount->discount_title}}</td>
                                        <td>
                                            @if($discount->product==null)
                                             {{$discount->promo_code or "All Product"}}
                                            @elseif(!$discount->product==null)
                                            {{str_before($discount->product->product_sku," | ")}}
                                            <br>{{str_after($discount->product->product_sku," | ")}} @endif
                                        </td>

                                        <td>{{date('d-M-Y',strtotime($discount->offer_from))}}
                                            <br>
                                            <br> {{date('d-M-Y',strtotime($discount->offer_to))}}
                                        </td>

                                        <td>{{$discount->discount_percent ? ($discount->discount_percent*100).' %' : 'tk.
                                            '.$discount->discount_amount}} </td>

                                        <td>
                                       
                                            <form action="{{route('change_discount_status',$discount->id)}}" method="post">
                                                @csrf
                                                <input type="hidden" name="status" value="{{$discount->status}}">
                                                <button type="submit" onclick="return confirm('Are you sure to change Status??')"
                                                    class="btn btn-link">
                                                    @if($discount->status == 1)
                                                    <span class="badge badge-success"><i class="mdi mdi-thumb-up"></i></span> @else
                                                    <span class="badge badge-danger"><i class="mdi mdi-thumb-down"></i></span> @endif
                                                </button>
                                            </form>
                                        </td>
                                        <td>
                                        <span class="input-group-append">
                                            <form action="{{route('discount_offers.destroy',$discount->id)}}" method="post">
                                                @csrf @method('delete')
                                                <a href="{{route('discount_offers.edit',$discount->id)}}" class="btn btn-dark btn-sm"><i class="mdi mdi-table-edit"></i></a>
                                                <button type="submit"  onclick="return confirm('Are you sure to delete this??')"
                                                    class="btn btn-danger btn-sm"><i class="mdi mdi-delete"></i></button>

                                            </form>
                                        </span>

                                        </td>
                                    </tr>
                                    @empty
                                    <tr>
                                        <td colspan="8">There is no records available</td>
                                    </tr>
                                    @endforelse
                                </tbody>
                            </table>
                    
                            {{--pagination--}}
                            <span class="float-right">{{$discount_index->links()}}</span>
                        </div>

                    </div>

                </div>
            </div>
        </div>
    </div>

</div>

@endsection