routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/* Route::any('{url_param}', function() {
    abort(403, '404 Error. Page not found!');
})->where('url_param', '.*'); */

Route::post('pdfreport','SaleController@pdf')->name('pdfreport'); //PDF report test

Route::get('/reset',function ()
{
	return view('auth.passwords.reset');
});
Route::get('/user/registration', 'UserController@user_register')->name('user.registration');
Route::post('/user/registration', 'UserController@user_register_store')->name('user.registration');

// Auth::routes('register');

 // Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
// Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
// Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::get('/laravel_chart', 'ChartDataController@getMonthlyPostData');

Route::group(['middleware'=>'auth'],function(){
	Route::get('/', 'HomeController@index')->name('/');
	Route::get('profile','UserController@profile')->name('profile');
	Route::post('profile.update','UserController@update_avatar')->name('profile.update');
	Route::resource('warranty_type','WarrantyTypeController');
	Route::resource('categories','CategoryController');
	
	Route::resource('branches','BranchController');
	
	Route::resource('suppliers','SupplierController');
	Route::post('supplier_beginning_balance','SupplierController@supplierBeginningBalance');
	Route::resource('sales_man','SalesManController');
	Route::get('show_invoice/{id}','SupplierController@show_invoice')->name('show_invoice');
	Route::get('monthly_status_of_supplier','SupplierController@monthlyStatusOfSupplier')->name('monthly_status_of_supplier');
	Route::resource('customer_groups','CustomerGroupController');
	Route::resource('customers','CustomerController');
	Route::get('monthly_status_of_customer','CustomerController@monthlyStatusOfCustomer')->name('monthly_status_of_customer');
	Route::post('customer_beginning_balance','CustomerController@customerBeginningBalance');
	Route::get('customer_invoice_show/{id}','CustomerController@customer_invoice_show')->name('customer_invoice_show');
	Route::resource('attribute_sets','AttributeSetController');
	Route::resource('attributes','AttributeController');
	Route::resource('vat','VatController');
	Route::resource('brand','BrandController');
	Route::resource('bundle_product','BundleProductController');
	Route::post('change_status/{id}','BundleProductController@change_status')->name('change_status');
	Route::get('getPrice/{id}','BundleProductController@get_price');
	//Route::resource('bundle_product_details','BundleProductDetailController');
	Route::resource('transactions','TransactionController');
	Route::get('transaction_status_show/{ridtype}','TransactionController@transaction_status_show')->name('transaction_status_show');
	
	Route::resource('products','ProductController');
	Route::get('barcode','ProductController@barcodeget')->name('barcode');
	Route::get('product_tracking','ProductController@productTracking')->name('product_tracking');
	Route::post('barcode','ProductController@barcodepost')->name('barcode');
	Route::resource('expire_products','ExpirableProductDetailController');
	Route::get('datatable','PurchaseController@getIndex');
	Route::get('datatabledata','PurchaseController@anyData');
	Route::get('show_invoice_details/{invoice_no}','PurchaseController@show_invoice_details')->name('show_invoice_details');
	Route::resource('purchases','PurchaseController');
	Route::get('purchase_history/{id}','BranchInventoryController@purchase_history')->name('purchase_history');
	Route::resource('trial_balance','AccountController');
	Route::get('income_report','AccountController@income_report');
	Route::resource('purchase_returns','PurchaseReturnController');
	Route::resource('journals','JournalController');
	Route::get('attributes_set_ajaxdata/{attr_set_id}','AttributeSetController@ajaxDataAttr');
	Route::get('warranty_type_data','WarrantyTypeController@warrenty_data');
	Route::resource('payment_method','PaymentMethodController');
	Route::post('add_payment_method_balance','PaymentMethodController@add_payment_method_balance');

	Route::resource('sales','SaleController');
	Route::resource('sales_return','SaleReturnController');
	Route::get('sales_report','SaleController@sales_report')->name('sales_report');
	Route::get('purchase_history_for_return','PurchaseReturnController@purchase_history_for_return');
	Route::get('sales_history_for_return','SaleReturnController@sales_history_for_return');
	Route::get('sales_details_report/{id}','SaleController@sales_details_report')->name('sales_details_report');
	Route::get('get_customer','SaleController@get_customer')->name('get_customer');
	Route::get('productSearch/{searchBy}','SaleController@productSearch')->name('productSearch');


	Route::get('add_to_cart/{productid}/{purchaseid}/{cust_group_id?}','SaleController@add_item_to_cart')->name('add_to_cart');
	Route::get('hold_customer_cart','SaleController@holdCustomerCart')->name('hold_customer_cart');
	Route::get('hold_back_customer_cart','SaleController@holdBackCustomerCart')->name('hold_back_customer_cart');
	Route::get('add_to_cart_bundle/{productid}','SaleController@add_bundle_item_to_cart')->name('add_to_cart_bundle');
	Route::get('update_cart_quentity/{rowid}/{qty}','SaleController@update_cart_quentity')->name('update_cart_quentity');
	Route::get('update_cart_discount/{coupon_no}','SaleController@update_cart_discount')->name('update_cart_discount');
	Route::get('set_customer_info/{customer_search_input}','SaleController@set_customer_info')->name('set_customer_info');
	Route::get('remove_item/{rowid}','SaleController@remove_item')->name('remove_item');
	Route::get('payment_model/{hello}','SaleController@returnCartTable')->name('payment_model');
	Route::get('view_product_details/{product_id}','SaleController@view_product_details')->name('view_product_details');
	Route::get('product_details/{product_id}','ProductController@get_product_details')->name('product_details');
	Route::get('invoice_details/{invoice}','PurchaseController@get_invoice_details')->name('invoice_details');
	Route::get('view_bundle_product_details/{product_id}','SaleController@view_bundle_product_details')->name('view_bundle_product_details');

	Route::resource('inventories','BranchInventoryController');
	Route::get('inventories_cart/{id}','BranchInventoryController@addToCart');

	Route::resource('discount_offers',"DiscountOfferController");
	Route::resource('customer_criterias',"CustomerCriteriaController");
	Route::resource('cheque_infos',"ChequeInfoController");
	Route::post('change_criteria_status/{id}','CustomerCriteriaController@criteria_status')->name('change_criteria_status');
	Route::post('change_discount_status/{id}','DiscountOfferController@discount_status')->name('change_discount_status');
	Route::get('find_purchase_id/{product_id}','DiscountOfferController@ajaxpurchaseid')->name('find_purchase_id');
	Route::get('find_product_for_discount/{product_id}/{invoice_no}','DiscountOfferController@find_product_for_discount')->name('find_product_for_discount');
	Route::post('change_user_status/{id}','HomeController@change_status')->name('change_user_status');
	Route::resource('warranty_product_detail','WarrantyProductDetailController');
	Route::get('expense_show','PrimarySettingsController@expenseShow')->name('expense_show');
	Route::get('payment_show','TransactionController@paymentShow')->name('payment_show');
	Route::get('record_expense','PrimarySettingsController@expenseCreate')->name('record_expense');
	Route::resource('primary_settings','PrimarySettingsController');
	Route::resource('invoice_setting','InvoiceSettingController');
	//Route::get('find_purchase_details/{product_purchase_id}','DiscountOfferController@ajaxpurchasedetails');
	//Route::get('sales/test/{sale}','SaleController@show')->name('sales.show');
	Route::get('/laravel_google_chart', 'HomeController@googlepiechart');
	Route::get('inventory_details/{id}','HomeController@show')->name('dashboard.branch');
});

resources/views/admin/sales_return/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
<div class="col-md-12 d-flex align-items-stretch grid-margin">
  <div class="row flex-grow">
	<div class="col-md-7">
	  <div class="card">
		<div class="card-body">
            <h4 class="card-title">Sales Return from Here</h4>
            <form class="forms-sample" method="post" action="{{route('sales_return.store')}}" enctype="multipart/form-data">
              @csrf
           
              <div class="form-group">
                <label for="supplier_id">Customer</label>
                <select  class="form-control" id="customer_id" name="customer_id" onchange="get_invoice()">
                <option value="">Select Customer</option>
               @forelse($customers as $sp)
               <option value="{{$sp->id}}">{{$sp->customer_name}}</option>
               @empty
               <option>{{'There is no Customer'}}</option>
               @endforelse
               </select>
             </div>

            <div class="form-group" id="invoice_no_select">
            </div>
            
            
          
             <div class="form-group" id="product_select">
               
                
                
              </div>
              <input type="hidden" class="form-control" name="purchase_id" id="purchase_id" value="">
                {{-- <input type="hidden" class="form-control" name="payment_method_id" id="payment_method_id" value="0"> --}}
                <input type="hidden" class="form-control" name="branch_inv_id" id="branch_id" value="">
                <input type="hidden" class="form-control" name="discount_rate" id="discount_rate" value="">

              <div class="form-group">
                <label for="returned_qty">Sold Quantity</label>
                <input type="number" class="form-control" name="returned_qty" id="returned_qty" onchange="getprice()">
                <input type="hidden" class="form-control" name="remain_qty" id="remain_qty">
              </div>
              <div class="form-group">
                <label for="discount">Discount</label>
                <input type="number" class="form-control" name="discount" value="0" id="discount" onchange="getprice()">
              </div>
              <div class="form-group">
                <label for="p_unit_price">Sold per Unit Price</label>
                <input readonly type="number" class="form-control" name="p_unit_price" id="p_unit_price" onchange="getprice()">
              </div>
            
           <div class="form-group">
                <label for="total_price">Amount to be paid</label>
                <input type="number" class="form-control" name="total_price" id="total_price" value="" readonly>
            </div>
            <div class="form-group">
              <label for="payment_method_id">Payment Method</label>
              <select required class="form-control" id="payment_method_id" name="payment_method_id"  onchange="addpaidvalue()">
              <option value="">Select Payment Method</option>
              <option value="0 | 0">Due</option>
               @foreach($payment_methods as $pm)
               <option value="{{$pm->id." | ".$pm->method_type}}">{{$pm->method_title}}</option>
               @endforeach
             </select>
           </div>
           <!--form group for paid amount-->
            <div class="form-group" id="payment_tk">
               
            </div>
            <div class="form-group" id="date_field">
               
            </div>
            
          
           <button type="submit" class="btn btn-success mr-2">Submit</button>
           <a class="btn btn-light" href="{{route('purchase_returns.index')}}">Cancel</a>
         </form>
       </div>
	  </div>
	</div>
 
  </div>
</div>

</div>


<script>
//multiply unit price n qty
 function getprice(){
 var p_unit_price = document.getElementById("p_unit_price").value;
 var discount = document.getElementById("discount").value;
 var returned_qty = document.getElementById("returned_qty").value;
 var total_price =returned_qty*(p_unit_price-discount);
  
    $('#total_price').val(total_price);
 }




 //check for invoice and supplier basis purchased history.
 function get_sales_history(){
  
var sales_id= document.getElementById("invoice_no").value;
var customer_id = document.getElementById("customer_id").value;
var product_id = document.getElementById("product_id").value;
var histry=product_id;
//check for warranty
 if(sales_id && customer_id){
          $.ajax({
                type:'GET',
                url:"<?=url('sales_history_for_return')?>",
                data:"histry="+histry,
                success:function(html){
                  var discountOnTotal=(html.sale.discount_total+html.sale.regular_discount_total)/html.sale.total_amount;
                  var discountPerQty=Math.round((html.sold_unit_price*discountOnTotal)+(html.discount_subtotal/html.sold_quantity));

                    $('#purchase_id').attr('value',html.purchase_id);
                    $('#returned_qty').attr('value',html.sold_quantity);
                    $('#remain_qty').attr('value',html.sold_quantity);
                    $('#p_unit_price').attr('value',html.sold_unit_price);
                    $('#discount').attr('value',discountPerQty);
                    $('#total_price').attr('value',(html.sold_unit_price-discountPerQty)*html.sold_quantity);
                    $('#branch_id').attr('value',html.branch_id);
                    
                    $('#discount_rate').attr('value',discountOnTotal);
                    
                  }
            });
        }else{
          alert("select Customer & invoice No First");
        }
 }


 //input field for invoice
 function get_invoice(){
  $('#invoice_no_select').empty();
    var customer_id = document.getElementById("customer_id").value;
    $.ajax({
            type:'GET',
            url:"<?=url('sales_history_for_return')?>",
            data:"customer_id="+customer_id,
            success:function(html){
              var showProduct="<label for='invoice_no'>Invoice</label><select name='invoice_no' id='invoice_no' class='form-control' onchange='get_product()'><option value=''>Select Invoice No.</option>";
                    var i=0;
                    var getLen=html.length;
                    while(i<getLen){
                      showProduct+="<option value='"+html[i].id+"'>"+html[i].invoice_no+"</option>";
                      i++;
                    }
                    showProduct+="</select>";
                    $('#invoice_no_select').append(showProduct);
                    
                }
    });
    }

 function get_product(){
  $('#product_select').empty();
    var sales_id= document.getElementById("invoice_no").value;
    var histry=sales_id;
    $.ajax({
            type:'GET',
            url:"<?=url('sales_history_for_return')?>",
            data:"condition="+histry,
            success:function(html){
              console.log(html.length);
              var showProduct="<label for='product_id'>Product</label><select name='product_id' id='product_id' class='form-control' onchange='get_sales_history()'><option value=''>Select Product</option>";
                    var i=0;
                    var getLen=html.length;
                    while(i<getLen){
                      showProduct+="<option value='"+html[i].product.id+'|'+html[i].id+"'>"+html[i].product.product_sku+"</option>";
                      i++;
                    }
                    showProduct+="</select>";
                    $('#product_select').append(showProduct);
                }
    });
    }
    function addpaidvalue() {
      var payment_method_id = document.getElementById("payment_method_id").value;
      $('#payment_tk').empty();
      payment_method_id = payment_method_id.split(" | ");
      if (payment_method_id[0]>0) {
          var paid_amount = "<label for='paid_amount'>Paid Amount</label>";
          paid_amount += "<input type='number' class='form-control' name='paid_amount' id='paid_amount'>";
          if (payment_method_id[1] == 1) {
              paid_amount +=
                  "<label for='check_no'>Check No <i class='text-danger'>( Optional )</i></label><input type='text' class='form-control' name='check_no' id='check_no' onchange='check_disposal_field()'>";
          }
          $('#payment_tk').prepend(paid_amount);
        }
}
//extra field for cheque disposal date 
function check_disposal_field() {
    var payment_method_id = document.getElementById("payment_method_id").value;
    $('#date_field').empty(paid_amount);
    payment_method_id = payment_method_id.split(" | ");
    if (payment_method_id[1] == 1) {
        var paid_amount =
            "<label for='cheque_disposal_date'>Cheque Disposal Date <i class='text-danger'>( Set if not Today )</i></label>";
        paid_amount +=
            "<input type='date' class='form-control' name='cheque_disposal_date' id='cheque_disposal_date'>";
        $('#date_field').prepend(paid_amount);
    }
  }
      
</script>
@endsection

resources/views/admin/sales_return/index.blade.php
@extends('layouts.admin')

@section('content')

<div class="row">
<div class="col-md-12 d-flex align-items-stretch grid-margin">
  <div class="row flex-grow row_table_responsive">
	<div class="col-md-12">
	  <div class="card">
		<div class="card-body">
      <h2 class="text-center">Sales Return History</h2>
      @if(Auth::user()->user_type=="superadmin")
            <h4 class="text-center">Showing All Branches</h4>
            @else
            <h4 class="text-center">Showing {{Auth::user()->branch->name}} Branch</h4>
            @endif
            <p class="card-description text-center">
                <form method="get" action="{{route('sales_return.index')}}">
                    <div class="input-group col-md-6 float-right">
                        <label for="example-search-input1">From :</label>
                        <input class="form-control py-2" @if(isset($_GET['searchbyfrom']))
                            value="{{$_GET['searchbyfrom']}}" @else value="{{date('Y-m-01')}}" @endif
                            name="searchbyfrom" type="date" id="example-search-input1">
                        <label for="example-search-input2">To :</label>
                        <input class="form-control py-2" placeholder="To.." name="searchbyto" type="date"
                            id="example-search-input2" @if(isset($_GET['searchbyto']))
                            value="{{$_GET['searchbyto']}}" @else value="{{date('Y-m-t')}}" @endif>
                        <span class="input-group-append">
                            <button class="btn btn-primary" type="submit">
                                <i class="mdi mdi-magnify"></i>
                            </button>
                        </span>

                    </div>
                </form>
            </p>
		  <div class="table-responsive">
                    <table class="table table-bordered">
                      <thead>
                        <tr>
                          <th>ID</th>
                          <th>Date</th>
                          <th>Product Sku</th>
                          <th class="text-right">Qty</th>
                          <th class="text-right">Unit price</th>
                          <th class="text-right">Discount</th>
                          <th class="text-right">SubTotal</th>
                          <th>Customer</th>
                          <th>Accepted by</th>
                        </tr>
                      </thead>
                      <tbody>
            <?php $i =1;
            $total=0; ?>
					  @forelse($sales_returns as $pr)
              <tr>
                <td>{{$i++}}</td>
                  <?php $time=strtotime($pr->created_at);
                  $date=date("d-M-Y",$time);
                  $timm=date("h:i:s",$time);?>
                <td title="{{$timm}}">{{$date}}</td>
                <td>{{ rtrim($pr->sale_details->product->product_sku,'|') }}</td>
                <td class="text-right">{{$pr->sold_return_quantity}}</td>
                <td class="text-right">{{$pr->sold_return_unit_price}}</td>
                <td class="text-right">{{$pr->returned_discount_rate}}</td>
                <?php
                $subtotal=$pr->sold_return_quantity*($pr->sold_return_unit_price-$pr->returned_discount_rate);
                $total=$total+$subtotal;?>
                <td  class="text-right">{{number_format($subtotal,2)}}</td>
                <td >{{$pr->sale_details->sale->customer->customer_name}}</td>
                <td title="{{$pr->users->name}}">{{$pr->users->user_type}}</td>
              </tr>
					@empty
						<tr>
							<td colspan="8">There is no records available</td>
						</tr>
					@endforelse
            </tbody>
            <tfoot>
              <th colspan="6" class="text-center">Total sales Return Amount:</th>
              <th class="text-right">Tk. {{number_format($total,2)}}</th>
              <th></th>
              <th></th>
            </tfoot>
          </table>
        </div>
		</div>
	  </div>
	</div>
  </div>
</div>

</div>

@endsection