routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/* Route::any('{url_param}', function() {
    abort(403, '404 Error. Page not found!');
})->where('url_param', '.*'); */

Route::post('pdfreport','SaleController@pdf')->name('pdfreport'); //PDF report test

Route::get('/reset',function ()
{
	return view('auth.passwords.reset');
});
Route::get('/user/registration', 'UserController@user_register')->name('user.registration');
Route::post('/user/registration', 'UserController@user_register_store')->name('user.registration');

// Auth::routes('register');

 // Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
// Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
// Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::get('/laravel_chart', 'ChartDataController@getMonthlyPostData');

Route::group(['middleware'=>'auth'],function(){
	Route::get('/', 'HomeController@index')->name('/');
	Route::get('profile','UserController@profile')->name('profile');
	Route::post('profile.update','UserController@update_avatar')->name('profile.update');
	Route::resource('warranty_type','WarrantyTypeController');
	Route::resource('categories','CategoryController');
	
	Route::resource('branches','BranchController');
	
	Route::resource('suppliers','SupplierController');
	Route::post('supplier_beginning_balance','SupplierController@supplierBeginningBalance');
	Route::resource('sales_man','SalesManController');
	Route::get('show_invoice/{id}','SupplierController@show_invoice')->name('show_invoice');
	Route::get('monthly_status_of_supplier','SupplierController@monthlyStatusOfSupplier')->name('monthly_status_of_supplier');
	Route::resource('customer_groups','CustomerGroupController');
	Route::resource('customers','CustomerController');
	Route::get('monthly_status_of_customer','CustomerController@monthlyStatusOfCustomer')->name('monthly_status_of_customer');
	Route::post('customer_beginning_balance','CustomerController@customerBeginningBalance');
	Route::get('customer_invoice_show/{id}','CustomerController@customer_invoice_show')->name('customer_invoice_show');
	Route::resource('attribute_sets','AttributeSetController');
	Route::resource('attributes','AttributeController');
	Route::resource('vat','VatController');
	Route::resource('brand','BrandController');
	Route::resource('bundle_product','BundleProductController');
	Route::post('change_status/{id}','BundleProductController@change_status')->name('change_status');
	Route::get('getPrice/{id}','BundleProductController@get_price');
	//Route::resource('bundle_product_details','BundleProductDetailController');
	Route::resource('transactions','TransactionController');
	Route::get('transaction_status_show/{ridtype}','TransactionController@transaction_status_show')->name('transaction_status_show');
	
	Route::resource('products','ProductController');
	Route::get('barcode','ProductController@barcodeget')->name('barcode');
	Route::get('product_tracking','ProductController@productTracking')->name('product_tracking');
	Route::post('barcode','ProductController@barcodepost')->name('barcode');
	Route::resource('expire_products','ExpirableProductDetailController');
	Route::get('datatable','PurchaseController@getIndex');
	Route::get('datatabledata','PurchaseController@anyData');
	Route::get('show_invoice_details/{invoice_no}','PurchaseController@show_invoice_details')->name('show_invoice_details');
	Route::resource('purchases','PurchaseController');
	Route::get('purchase_history/{id}','BranchInventoryController@purchase_history')->name('purchase_history');
	Route::resource('trial_balance','AccountController');
	Route::get('income_report','AccountController@income_report');
	Route::resource('purchase_returns','PurchaseReturnController');
	Route::resource('journals','JournalController');
	Route::get('attributes_set_ajaxdata/{attr_set_id}','AttributeSetController@ajaxDataAttr');
	Route::get('warranty_type_data','WarrantyTypeController@warrenty_data');
	Route::resource('payment_method','PaymentMethodController');
	Route::post('add_payment_method_balance','PaymentMethodController@add_payment_method_balance');

	Route::resource('sales','SaleController');
	Route::resource('sales_return','SaleReturnController');
	Route::get('sales_report','SaleController@sales_report')->name('sales_report');
	Route::get('purchase_history_for_return','PurchaseReturnController@purchase_history_for_return');
	Route::get('sales_history_for_return','SaleReturnController@sales_history_for_return');
	Route::get('sales_details_report/{id}','SaleController@sales_details_report')->name('sales_details_report');
	Route::get('get_customer','SaleController@get_customer')->name('get_customer');
	Route::get('productSearch/{searchBy}','SaleController@productSearch')->name('productSearch');


	Route::get('add_to_cart/{productid}/{purchaseid}/{cust_group_id?}','SaleController@add_item_to_cart')->name('add_to_cart');
	Route::get('hold_customer_cart','SaleController@holdCustomerCart')->name('hold_customer_cart');
	Route::get('hold_back_customer_cart','SaleController@holdBackCustomerCart')->name('hold_back_customer_cart');
	Route::get('add_to_cart_bundle/{productid}','SaleController@add_bundle_item_to_cart')->name('add_to_cart_bundle');
	Route::get('update_cart_quentity/{rowid}/{qty}','SaleController@update_cart_quentity')->name('update_cart_quentity');
	Route::get('update_cart_discount/{coupon_no}','SaleController@update_cart_discount')->name('update_cart_discount');
	Route::get('set_customer_info/{customer_search_input}','SaleController@set_customer_info')->name('set_customer_info');
	Route::get('remove_item/{rowid}','SaleController@remove_item')->name('remove_item');
	Route::get('payment_model/{hello}','SaleController@returnCartTable')->name('payment_model');
	Route::get('view_product_details/{product_id}','SaleController@view_product_details')->name('view_product_details');
	Route::get('product_details/{product_id}','ProductController@get_product_details')->name('product_details');
	Route::get('invoice_details/{invoice}','PurchaseController@get_invoice_details')->name('invoice_details');
	Route::get('view_bundle_product_details/{product_id}','SaleController@view_bundle_product_details')->name('view_bundle_product_details');

	Route::resource('inventories','BranchInventoryController');
	Route::get('inventories_cart/{id}','BranchInventoryController@addToCart');

	Route::resource('discount_offers',"DiscountOfferController");
	Route::resource('customer_criterias',"CustomerCriteriaController");
	Route::resource('cheque_infos',"ChequeInfoController");
	Route::post('change_criteria_status/{id}','CustomerCriteriaController@criteria_status')->name('change_criteria_status');
	Route::post('change_discount_status/{id}','DiscountOfferController@discount_status')->name('change_discount_status');
	Route::get('find_purchase_id/{product_id}','DiscountOfferController@ajaxpurchaseid')->name('find_purchase_id');
	Route::get('find_product_for_discount/{product_id}/{invoice_no}','DiscountOfferController@find_product_for_discount')->name('find_product_for_discount');
	Route::post('change_user_status/{id}','HomeController@change_status')->name('change_user_status');
	Route::resource('warranty_product_detail','WarrantyProductDetailController');
	Route::get('expense_show','PrimarySettingsController@expenseShow')->name('expense_show');
	Route::get('payment_show','TransactionController@paymentShow')->name('payment_show');
	Route::get('record_expense','PrimarySettingsController@expenseCreate')->name('record_expense');
	Route::resource('primary_settings','PrimarySettingsController');
	Route::resource('invoice_setting','InvoiceSettingController');
	//Route::get('find_purchase_details/{product_purchase_id}','DiscountOfferController@ajaxpurchasedetails');
	//Route::get('sales/test/{sale}','SaleController@show')->name('sales.show');
	Route::get('/laravel_google_chart', 'HomeController@googlepiechart');
	Route::get('inventory_details/{id}','HomeController@show')->name('dashboard.branch');
});

app/Purchase.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Purchase extends Model
{
    public function users() {
        return $this->belongsTo('App\User','created_by');
    }
    public function supplier() {
        return $this->belongsTo('App\Supplier','supplier_id');
    }
    public function product() {
        return $this->belongsTo('App\Product','product_id');
    }
    public function purchase_return() {
        return $this->hasMany('App\Purchase_return','purchase_id');
    }
    public function branch() {
        return $this->belongsTo('App\Branch','branch_id');
    }
    public function product_status() {
        return $this->hasOne('App\Branch_inventory','purchase_id');
    }
    public function bundle_product_details(){
        return $this->hasMany(Bundle_product_detail::class,'purchase_id');
    }
    public function product_warranty_types(){
        return $this->hasMany(Bundle_product_detail::class,'purchase_id');
    }
    public function warranty_types(){
        return $this->hasMany(Product_warranty_type::class);
    }
    public function inventories()
    {
        return $this->hasMany('App\Branch_inventory', 'purchase_id');
    }
    
    public function warranty_product_details()
    {
        return $this->hasMany('App\Warranty_product_detail', 'purchase_id');
    }
    public function sales_details()
    {
        return $this->hasMany('App\Sale_detail', 'purchase_id');
    }
    
    
}

resources/views/admin/purchase/datatable.blade.php
@extends('layouts.admin')
@section('content')
<div class="row">
        <div class="col-md-12 d-flex align-items-stretch grid-margin">
          <div class="row flex-grow row_table_responsive">
            <div class="col-md-12"><br>
                <div class="table-responsive">
                    <table class="datatableclass table table-striped table-hover" id="datatable">
                        <thead>
                            <tr>
                                <th>Date</th>
                                <th>Invoice No</th>
                                <th>Supplier</th>
                                <th>Qty</th>
                                <th>Created By</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
          </div>
        </div>
    </div>
@endsection
@push('js')
<script>
        $(function () {
            $('#datatable').DataTable({
                serverSide: true,
                processing: true,
                ajax: 'datatabledata',
                columns: [
                    {data: 'created_at'},
                    {data: 'invoice_no'},
                    {data: 'supplier.supplier_name'},
                    {data: 'Total'},
                    {data: 'users.name'},
                ]
            });
        });
    </script>
@endpush

resources/views/admin/purchase/edit.blade.php
@extends('layouts.admin')

@section('content')

<div class="row">
    <div class="col-md-6 d-flex align-items-stretch grid-margin">
        <div class="row flex-grow">
            <div class="col-12">
                <form class="forms-sample" method="post"
                action="{{route('purchases.update',$purchase->first()->id)}}">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Purchase Edit Form</h4>
                            @csrf
                            @method('put')
                            {{--Model-For-Edit-Invoice  --}}
                    <input type="hidden" name="invoice_no" value="{{$purchase->first()->invoice_no}}">
                            <div class="modal-body" id="exampleModalBody">
                                <table class="table table-striped table-bordered">
                                    <thead>
                                        <tr>
                                            <th>Product Name</th>
                                            <th>Qty</th>
                                            <th>Purchase Price</th>
                                            <th>Selling Price</th>
                                        </tr>
                                    </thead>
                                    <tbody id="editModalTable">
                                        @forelse ($purchase as $data)
                                        <tr>
                                            <input type="hidden" name="purchase_id[]" value="{{$data->id}}">
                                            <th>{{str_before($data->product->product_sku,'|')}}</th>
                                            <th><input type="number" name="quantity[]" class="form-control-sm"
                                                    value="{{$data->quantity}}"><input type="hidden" name="old_quantity[]" class="form-control-sm"
                                                    value="{{$data->quantity}}"></th>
                                            <th><input type="number" name="purchase_unit_price[]"
                                                    class="form-control-sm" value="{{$data->purchase_unit_price}}"><input type="hidden" name="old_purchase_unit_price[]"
                                                    class="form-control-sm" value="{{$data->purchase_unit_price}}"></th>
                                            <th><input type="number" name="sell_unit_price[]" class="form-control-sm"
                                                    value="{{$data->sell_unit_price}}"><input type="hidden" name="old_sell_unit_price[]" class="form-control-sm"
                                                    value="{{$data->sell_unit_price}}"></th>
                                        </tr>
                                        @empty

                                        @endforelse

                                    </tbody>
                                </table>
                            </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-success mr-2">Submit</button>
            
            {{-- <a href="{{route('categories.index')}}" class="btn btn-danger">Cancel</a> --}}
            </form>
            </div>
            {{--Model-For-Edit-Invoice  --}}

            
        </div>
    </div>
</div>


@endsection

resources/views/admin/purchase/report.blade.php
@extends('layouts.admin')

@section('content')

<div class="row">
    <div class="col-md-12 d-flex align-items-stretch grid-margin">
        <div class="row flex-grow row_table_responsive">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <h2 class="text-center">Purchase History</h2>
                        @if(Auth::user()->user_type=="superadmin")
                        <h4 class="text-center">Showing All Branches</h4>
                        @else
                        <h4 class="text-center">Showing {{Auth::user()->branch->name}} Branch</h4>
                        @endif
                        <p class="card-description text-center">
                            <form method="get" action="{{route('purchases.index')}}">
                                <div class="input-group col-md-6 float-right">
                                    <label for="example-search-input1">From :</label>
                                    <input class="form-control py-2" @if(isset($_GET['searchbyfrom']))
                                        value="{{$_GET['searchbyfrom']}}" @else value="{{date('Y-m-01')}}" @endif
                                        name="searchbyfrom" type="date" id="example-search-input1">
                                    <label for="example-search-input2">To :</label>
                                    <input class="form-control py-2" placeholder="To.." name="searchbyto" type="date"
                                        id="example-search-input2" @if(isset($_GET['searchbyto']))
                                        value="{{$_GET['searchbyto']}}" @else value="{{date('Y-m-t')}}" @endif>
                                    <span class="input-group-append">
                                        <button class="btn btn-primary" type="submit">
                                            <i class="mdi mdi-magnify"></i>
                                        </button>
                                    </span>

                                </div>
                            </form>
                        </p>
                        <div class="table-responsive">
                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th>Date</th>
                                        <th>Invoice No:</th>
                                        <th>Total Qty</th>
                                        <th>SubTotal</th>
                                        <th>Supplier</th>
                                        <th>Purchased by</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php 
                                        $i =1;
                                        $total=0;
                                    ?>
                                    @forelse ($purchases as $key => $purchase)
                                    <tr>
                                        <?php 
                                            $time=strtotime($purchase->first()->created_at);
                                            $date=date("d-M-Y",$time);
                                            $timm=date("h:i:s",$time);
                                        ?>
                                        <td title="{{$timm}}">{{$date}}</td>
                                        <td>
                                            <input type="button" value="{{$key}}"
                                                onclick="showInvoiceDetails(this.value)" data-toggle="modal"
                                                data-target="#exampleModalCenter">
                                        </td>
                                        <td>
                                            {{$purchase->sum('quantity')}}
                                        </td>
                                        <td>
                                            @php
                                            $totalPurchaseAmount=0;
                                                foreach($purchase as $purchaseData){
                                                    $totalPurchaseAmount=$totalPurchaseAmount+($purchaseData->quantity*$purchaseData->purchase_unit_price);
                                                }
                                            @endphp
                                            {{$totalPurchaseAmount}}
                                        </td>
                                        <td>{{$purchase->first()->supplier->supplier_name}}</td>
                                        <td title="{{$purchase->first()->users->name}}">{{$purchase[0]->users->user_type}}
                                        </td>
                                        <td>
                                                @php
                                                $showing=true;
                                                @endphp
                                            @foreach($purchase as $purchaseData)
                                            @if(count($purchaseData->sales_details)>0)
                                                @php
                                                    $showing=false;
                                                @endphp
                                                @endif
                                            @endforeach
                                                @if($showing)
                                            <a class="btn btn-info" href="{{route('show_invoice_details',$key)}}?iseditable=true"><i class="mdi mdi-pencil"></i></a>
                                                @else
                                                <button class="btn btn-info"  type="button" disabled="true"><i class="mdi mdi-pencil"></i></button>
                                                @endif
                                        </td>
                                    </tr>
                                    @empty
                                    <tr>
                                        <td colspan="8">There is no records available</td>
                                    </tr>
                                    @endforelse
                                </tbody>
                                <tfoot>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="exampleModalBody">
                <table class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>Product Name</th>
                            <th>Qty</th>
                            <th>Purchase Price</th>
                            <th>Selling Price</th>
                        </tr>
                    </thead>
                    <tbody id="exampleModalTable">
                    </tbody>
                </table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
 {{--Model-For-Edit-Invoice  --}}
 <div class="modal fade" id="editInvoiceModal" tabindex="-1" role="dialog" aria-labelledby="editInvoiceModalTitle"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editModalTableTitle">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="exampleModalBody">
                <table class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>Product Name</th>
                            <th>Qty</th>
                            <th>Purchase Price</th>
                            <th>Selling Price</th>
                        </tr>
                    </thead>
                    <tbody id="editModalTable">
                    </tbody>
                </table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
@endsection
@push('js')
    <script>
      // show Invoice details
      function showInvoiceDetails(invoice_no){
        var route = "{{url('')}}/show_invoice_details/"+invoice_no;
        $('#exampleModalLongTitle').text("Invoice No: "+invoice_no);
        $.get(route,function(data){
          console.log(data);
          $('#exampleModalTable').empty();
          var tr = "<tr>";
          for(i=0;i<data.length;i++){
            tr += "<td>"+data[i].product.product_sku.split("|")[0]+"</td>";
            tr += "<td>"+data[i].quantity+"</td>";
            tr += "<td>"+data[i].purchase_unit_price+"</td>";
            tr += "<td>"+data[i].sell_unit_price+"</td>";
            tr += "</tr>";
          }
          $('#exampleModalTable').html(tr);
        });
      }

      // show Invoice Details For Edit
    //   function showInvoiceDetailsForEdit(invoice_no){
    //     var route = "{{url('')}}/show_invoice_details/"+invoice_no;
    //     var actionurl = "{{url('')}}/show_invoice_details/"+invoice_no;
    //     $('#editModalTableTitle').text("Invoice No: "+invoice_no);
    //     $.get(route,function(data){
    //       console.log(data);
    //       $('#editModalTable').empty();
    //       var tr = "<tr><form method='post' action='"+actionurl+"'>";
    //       for(i=0;i<data.length;i++){
    //         tr += "<td>"+data[i].product.product_sku.split("|")[0]+"</td>";
    //         tr += "<td><input type='number' size='3' name='new_qty[]' class='form-control-sm' value='"+data[i].quantity+"'><input type='hidden'  name='old_qty[]'  value='"+data[i].quantity+"'></td>";
    //         tr += "<td><input type='number' size='3' name='new_purchase_unit_price[]' class='form-control-sm' value='"+data[i].purchase_unit_price+"'><input type='hidden'  name='old_purchase_unit_price[]' value='"+data[i].purchase_unit_price+"'></td>";
    //         tr += "<td><input type='number' size='3' name='new_sell_unit_price[]' class='form-control-sm' value='"+data[i].sell_unit_price+"'><input type='hidden'  name='old_sell_unit_price[]' value='"+data[i].sell_unit_price+"'></td>";
    //         tr += "</form></tr>";
    //       }
    //       $('#editModalTable').html(tr);
    //     });
    //   }
    </script>
@endpush

resources/views/admin/purchase/reportpdf.blade.php
<!-- inject:css -->
<link rel="stylesheet" href="{{asset('admin')}}/css/style.css">

<div class="row">
<div class="col-md-12 d-flex align-items-stretch grid-margin">
  <div class="row flex-grow row_table_responsive">
	<div class="col-md-12">
	  <div class="card">
		<div class="card-body">
		  <h4 class="text-center">Purchase History</h4>
		  <div class="table-responsive">
                    <table class="table table-bordered">
                      <thead>
                        <tr>
                          <th>ID</th>
                          <th>Date</th>
                          <th>Product Sku</th>
                          <th>Qty</th>
                          <th>unit price</th>
                          <th>SubTotal</th>
                          <th>Supplier</th>
                          <th>Purchased by</th>
                        </tr>
                      </thead>
                      <tbody>
            <?php $i =1;
            $total=0; ?>
					  @forelse($purchases as $cat)
                        <tr>
                          <td>{{$i++}}</td>
                          <?php $time=strtotime($cat->created_at);
                            $date=date("d-M-Y",$time);
                            $timm=date("h:i:s",$time);?>
                            <td title="{{$timm}}">{{$date}}</td>
                          <td>{{str_before($cat->product->product_sku,"|")}}<br>{{str_after($cat->product->product_sku,"|")}}</td>
                          <td>{{$cat->quantity}}</td>
                          <td>{{$cat->purchase_unit_price}}</td>
                          <?php
                          $subtotal=$cat->quantity*$cat->purchase_unit_price;
                          $total=$total+$subtotal;?>
                          <td>tk. {{$subtotal}}</td>
                          <td>{{$cat->supplier->supplier_name}}</td>
                          <td title="{{$cat->users->name}}">{{$cat->users->user_type}}</td>
                          <!-- <td>
                            <a href="{{route('attribute_sets.edit',$cat->id)}}" class="btn btn-link">Edit</a>
							            </td> -->
                        </tr>
					@empty
						<tr>
							<td colspan="8">There is no records available</td>
						</tr>
					@endforelse
                      </tbody>
                      <tfoot>
                        <th colspan="5" class="text-right">Total Purchased Amount:</th>
                        <th colspan="3" class="text-left">tk. {{$total}}</th>
                        
                      </tfoot>
                    </table>
                  </div>
		</div>
	  </div>
	</div>
  </div>
</div>

</div>